-- MySQL Script generated by MySQL Workbench
-- Mon Mar  9 11:25:28 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`items` (
  `item_id` INT(11) NOT NULL,
  `item_name` VARCHAR(150) NOT NULL,
  `category` VARCHAR(100) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `PRICE` VARCHAR(100) NULL DEFAULT NULL,
  `Quantity` VARCHAR(100) NULL DEFAULT NULL,
  `expiry_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`item_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` INT(11) NOT NULL,
  `full_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `role` VARCHAR(25) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`pharmacy_dispense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pharmacy_dispense` (
  `dispense_id` INT(11) NOT NULL,
  `item_id` INT(11) NOT NULL,
  `quantity` INT(11) NOT NULL,
  `dispensed_by` INT(11) NOT NULL,
  `dispensed_to` VARCHAR(100) NULL DEFAULT NULL,
  `dispense_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`dispense_id`),
  INDEX `fk_dispense_item` (`item_id` ASC) VISIBLE,
  INDEX `fk_dispense_user` (`dispensed_by` ASC) VISIBLE,
  CONSTRAINT `fk_dispense_item`
    FOREIGN KEY (`item_id`)
    REFERENCES `mydb`.`items` (`item_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dispense_user`
    FOREIGN KEY (`dispensed_by`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stock` (
  `stock_id` INT(11) NOT NULL,
  `item_id` INT(11) NOT NULL,
  `quantity` INT(11) NOT NULL DEFAULT 0,
  `last_updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`stock_id`),
  INDEX `fk_stock_item` (`item_id` ASC) VISIBLE,
  CONSTRAINT `fk_stock_item`
    FOREIGN KEY (`item_id`)
    REFERENCES `mydb`.`items` (`item_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`stock_in`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stock_in` (
  `stock_in_id` INT(11) NOT NULL,
  `item_id` INT(11) NOT NULL,
  `quantity` INT(11) NOT NULL,
  `received_by` INT(11) NOT NULL,
  `received_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`stock_in_id`),
  INDEX `fk_stockin_item` (`item_id` ASC) VISIBLE,
  INDEX `fk_stockin_user` (`received_by` ASC) VISIBLE,
  CONSTRAINT `fk_stockin_item`
    FOREIGN KEY (`item_id`)
    REFERENCES `mydb`.`items` (`item_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_stockin_user`
    FOREIGN KEY (`received_by`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`stock_out`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stock_out` (
  `stock_out_id` INT(11) NOT NULL,
  `item_id` INT(11) NOT NULL,
  `quantity` INT(11) NOT NULL,
  `issued_to` INT(11) NOT NULL,
  `issued_by` INT(11) NOT NULL,
  `issued_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`stock_out_id`),
  INDEX `fk_stockout_item` (`item_id` ASC) VISIBLE,
  INDEX `fk_stockout_issued_to` (`issued_to` ASC) VISIBLE,
  INDEX `fk_stockout_issued_by` (`issued_by` ASC) VISIBLE,
  CONSTRAINT `fk_stockout_issued_by`
    FOREIGN KEY (`issued_by`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_stockout_issued_to`
    FOREIGN KEY (`issued_to`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_stockout_item`
    FOREIGN KEY (`item_id`)
    REFERENCES `mydb`.`items` (`item_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`ward_requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ward_requests` (
  `request_id` INT(11) NOT NULL,
  `item_id` INT(11) NOT NULL,
  `requested_by` INT(11) NOT NULL,
  `quantity` INT(11) NOT NULL,
  `status` ENUM('Pending', 'Approved', 'Rejected', 'Issued') NULL DEFAULT 'Pending',
  `request_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`request_id`),
  INDEX `fk_wardreq_item` (`item_id` ASC) VISIBLE,
  INDEX `fk_wardreq_user` (`requested_by` ASC) VISIBLE,
  CONSTRAINT `fk_wardreq_item`
    FOREIGN KEY (`item_id`)
    REFERENCES `mydb`.`items` (`item_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_wardreq_user`
    FOREIGN KEY (`requested_by`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
